In [1]:
import cv2
import numpy as np

dst = cv2.imread('../image.jpg', 0)
h, w = dst.shape[:2]
dst_y, dst_x = np.indices((h, w))
dst_lin_homg_pts = np.stack((dst_x.ravel(), dst_y.ravel(), np.ones(dst_y.size)))

In [10]:
dst.shape

(3024, 3024)

In [7]:
dst_x

array([[   0,    1,    2, ..., 3021, 3022, 3023],
       [   0,    1,    2, ..., 3021, 3022, 3023],
       [   0,    1,    2, ..., 3021, 3022, 3023],
       ...,
       [   0,    1,    2, ..., 3021, 3022, 3023],
       [   0,    1,    2, ..., 3021, 3022, 3023],
       [   0,    1,    2, ..., 3021, 3022, 3023]])

In [4]:
dst_y

array([[   0,    0,    0, ...,    0,    0,    0],
       [   1,    1,    1, ...,    1,    1,    1],
       [   2,    2,    2, ...,    2,    2,    2],
       ...,
       [3021, 3021, 3021, ..., 3021, 3021, 3021],
       [3022, 3022, 3022, ..., 3022, 3022, 3022],
       [3023, 3023, 3023, ..., 3023, 3023, 3023]])

In [9]:
dst_lin_homg_pts.shape

(3, 9144576)

In [11]:
dst_lin_homg_pts

array([[0.000e+00, 1.000e+00, 2.000e+00, ..., 3.021e+03, 3.022e+03,
        3.023e+03],
       [0.000e+00, 0.000e+00, 0.000e+00, ..., 3.023e+03, 3.023e+03,
        3.023e+03],
       [1.000e+00, 1.000e+00, 1.000e+00, ..., 1.000e+00, 1.000e+00,
        1.000e+00]])

In [15]:
src_pts = np.float32([[693, 349], [605, 331], [445, 59]])
dst_pts = np.float32([[1379, 895], [1213, 970], [684, 428]])
transf = cv2.getAffineTransform(dst_pts, src_pts)
src_lin_pts = np.round(transf.dot(dst_lin_homg_pts).astype(int))

In [17]:
src_lin_pts.shape

(2, 9144576)

In [18]:
min_x, min_y = np.amin(src_lin_pts, axis=1)
src_lin_pts -= np.array([[min_x], [min_y]])

In [19]:
trans_max_x, trans_max_y = np.amax(src_lin_pts, axis=1)
src = np.ones((trans_max_y + 1, trans_max_x + 1), dtype=np.uint8) * 127

In [21]:
src[src_lin_pts[1], src_lin_pts[0]] = dst.ravel()

In [ ]:
cv2.imshow('src', src)
cv2.waitKey()